//`timescale 1ns / 1ps

//module ROPUF_counter(clk,rst,start,RO_select1,RO_select2,RO1_count,RO2_count);
//    input clk,rst;
//    input start;
//    input RO_select1,RO_select2;
//    output reg [26:0] RO1_count,RO2_count;
//    //output reg [1:0] PUF_sel;
    
//    //we counter a CDC problem for the stop signal
//    reg measurement_done;
//    //Counter 1
//    always @(posedge RO_select1 or posedge rst)    begin
//        if (rst)    begin
//            RO1_count<=0;
//        end
//        else if (start && !measurement_done)
//            RO1_count<=RO1_count+1;    
//    end
    
//    //Counter 2
//    always @(posedge RO_select2 or posedge rst)    begin
//        if (rst)    begin
//            RO2_count<=0;
//        end
//        else if (start && !measurement_done)
//            RO2_count<=RO2_count+1;    
//    end
    
//    reg [11:0] clk_count;
    
    
//    //Frequency calculation
//    always @(posedge clk)   begin
//        if (rst) begin
//            clk_count<=0;
//            //PUF_sel<=0;
//            measurement_done<=0;
//        end
//        else if (start && !measurement_done)   begin
//            clk_count<=clk_count+1;
            
//            if (clk_count==999-1) begin  //considering 10us as reference timeframe
//                measurement_done<=1;
//                clk_count<=0;
                
//            end
//            else measurement_done<=0;
//        end
//        //else clk_count<=0;
//    end
    
//endmodule

`timescale 1ns / 1ps

module ROPUF_counter #(parameter COUNTER_WIDTH = 10,parameter MEAS_CYCLES   = 1000)
    (input  clk,input rst,input start,input RO_select1,input RO_select2,
    output reg [COUNTER_WIDTH-1:0] RO1_count,
    output reg [COUNTER_WIDTH-1:0] RO2_count,
    output reg count_ready);

    /*
     * ============================================================
     * SYSTEM CLOCK DOMAIN
     * ============================================================
     */

    reg [11:0] clk_count;

    reg measurement_active;

    /*
     * Capture request generated by system clock.
     * This is synchronized into the RO domains.
     */
    reg capture_req;

    /*
     * Acknowledgement from RO domains.
     * These are synchronized back into the system domain.
     */
    reg capture_ack1;
    reg capture_ack2;

    reg capture_ack1_sync1;
    reg capture_ack1_sync2;

    reg capture_ack2_sync1;
    reg capture_ack2_sync2;


    /*
     * ============================================================
     * RO DOMAIN 1
     * ============================================================
     */

    reg [COUNTER_WIDTH-1:0] RO1_counter;
    reg [COUNTER_WIDTH-1:0] RO1_snapshot;

    reg capture_req1_sync1;
    reg capture_req1_sync2;


    /*
     * Synchronize capture request into RO1 domain
     */
    always @(posedge RO_select1 or posedge rst) begin

        if (rst) begin
            capture_req1_sync1 <= 1'b0;
            capture_req1_sync2 <= 1'b0;
        end
        else begin
            capture_req1_sync1 <= capture_req;
            capture_req1_sync2 <= capture_req1_sync1;
        end

    end


    /*
     * RO1 edge counter + snapshot
     */
    always @(posedge RO_select1 or posedge rst) begin
        if (rst) begin
            RO1_counter <= 0;
            RO1_snapshot <= 0;
            capture_ack1 <= 0;
        end
        else begin
            /*
             * Normal frequency counting
             */
            if (measurement_active)
                RO1_counter <= RO1_counter + 1'b1;
            /*
             * Capture final count
             */
            if (capture_req1_sync2 && !capture_ack1) begin
                RO1_snapshot <= RO1_counter;
                capture_ack1 <= 1'b1;
            end
            /*
             * Prepare acknowledgement for next measurement
             */
            if (!capture_req1_sync2)
                capture_ack1 <= 1'b0;
        end
    end


    /*
     * ============================================================
     * RO DOMAIN 2
     * ============================================================
     */

    reg [COUNTER_WIDTH-1:0] RO2_counter;
    reg [COUNTER_WIDTH-1:0] RO2_snapshot;

    reg capture_req2_sync1;
    reg capture_req2_sync2;


    /*
     * Synchronize capture request into RO2 domain
     */
    always @(posedge RO_select2 or posedge rst) begin

        if (rst) begin
            capture_req2_sync1 <= 1'b0;
            capture_req2_sync2 <= 1'b0;
        end
        else begin
            capture_req2_sync1 <= capture_req;
            capture_req2_sync2 <= capture_req2_sync1;
        end

    end


    /*
     * RO2 edge counter + snapshot
     */
    always @(posedge RO_select2 or posedge rst) begin

        if (rst) begin

            RO2_counter <= 0;
            RO2_snapshot <= 0;
            capture_ack2 <= 0;

        end
        else begin
            /*
             * Normal frequency counting
             */
            if (measurement_active)
                RO2_counter <= RO2_counter + 1'b1;
            /*
             * Capture final count
             */
            if (capture_req2_sync2 && !capture_ack2) begin
                RO2_snapshot <= RO2_counter;
                capture_ack2 <= 1'b1;
            end

            /*
             * Prepare acknowledgement for next measurement
             */
            if (!capture_req2_sync2)
                capture_ack2 <= 1'b0;

        end

    end


    /*
     * ============================================================
     * SYSTEM CLOCK DOMAIN
     * ============================================================
     */

    /*
     * Synchronize acknowledgements back to system clock
     */
    always @(posedge clk or posedge rst) begin

        if (rst) begin

            capture_ack1_sync1 <= 0;
            capture_ack1_sync2 <= 0;

            capture_ack2_sync1 <= 0;
            capture_ack2_sync2 <= 0;

        end
        else begin

            capture_ack1_sync1 <= capture_ack1;
            capture_ack1_sync2 <= capture_ack1_sync1;

            capture_ack2_sync1 <= capture_ack2;
            capture_ack2_sync2 <= capture_ack2_sync1;

        end

    end


    /*
     * ============================================================
     * MEASUREMENT CONTROLLER
     * ============================================================
     */

    always @(posedge clk or posedge rst) begin

        if (rst) begin

            clk_count         <= 0;
            measurement_active <= 0;

            capture_req <= 0;

            RO1_count <= 0;
            RO2_count <= 0;

            count_ready <= 0;

        end

        else begin

            /*
             * Start a new measurement
             */
            if (start && !measurement_active && !count_ready) begin

                clk_count <= 0;

                measurement_active <= 1'b1;

            end


            /*
             * Measurement is running
             */
            else if (measurement_active) begin

                if (clk_count == MEAS_CYCLES-1) begin

                    /*
                     * Stop normal counting
                     */
                    measurement_active <= 1'b0;

                    /*
                     * Ask RO domains to capture
                     * their final counter values
                     */
                    capture_req <= 1'b1;

                end
                else begin

                    clk_count <= clk_count + 1'b1;

                end

            end


            /*
             * Wait until BOTH RO domains have
             * acknowledged the capture
             */
            if (capture_ack1_sync2 &&
                capture_ack2_sync2) begin

                /*
                 * Now the snapshots are stable
                 */
                RO1_count <= RO1_snapshot;
                RO2_count <= RO2_snapshot;

                count_ready <= 1'b1;

                /*
                 * Finish this capture transaction
                 */
                capture_req <= 1'b0;

            end


            /*
             * Prepare for next measurement
             */
            if (!start && count_ready) begin

                count_ready <= 1'b0;

            end

        end

    end

endmodule